sudo: false

language: python

python:
  - "3.4"
  - "3.6"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run test.py

after_success:
  - codecov
  - coverage report -m

deploy:
  provider: pypi
  user: "irgang"
  password:
    secure: "K9uBtVY2XcGDb2rHJvkn8KwC9y8ITdeA/cuFDaWftaWy60qLdTWTYow+CahNFDdkNoC03+HZWth6vVSf2S5XALO/KhzBHgCYe6sPejXsCwHU+YYrxu2NmGB2qa0wyibNO/stRtmQ9JK9TFU87UdK3DTDfK2XeKiB4mh8KusV1PRpCtc9Gw/MzjE7x+90jXAb8dZjj+Igb5KIP5I01JYXSuqOChAR4dNr5MjgUrij8jAj5TT+/HcpxnVdlNYB
Ma7jZ8uiNIzOEUdVBcU38tZ6fxg6oCO3uVLwipGxYcso67ECQMKlBZDQgY2VvYXVjhY5f3qnR6BwemOVTx307lvBqDHGjL0RGZyGT/bRbwrCXsp3+mhWgS9hXyray/zmQadpSqnYvzPchlCNnGRudowDhPqv6/Oy9j8pPUZJekvgRbCb5JBO4eqAahfijuudzmjDtE+PYIhmuBQxAn5WkJcS1kL5vznWMLmJx+1ylovg42h/Z/0lQsFHCs1XA7rZKe2E8
ysNqDkJh5bdz/BMO/sJqIj0mDPoTY91xtZLCK3ydFJUNhmf65nC+Nak5mnEw3Hk96ynaCCDRhvXKulS5PqTaxNaG4GxRNkv1fcnQ7Z+pMWc8IRY43dCtvqUfd2c5ANlMT2R74zbpEmKHFI0Lg1uFQen35ea2euQLdcNjfLoFgM="
  on:
    tags: true
    branch: master
  distributions: "sdist"